#!/bin/bash

PACKAGE_NAME="quickjs-fltk-cffi"
PACKAGE_VER="0.1.0"

function prepare () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2
    local LOCAL_PACKAGE_PATH=$3

    git submodule update --init --recursive

    echo prepare $PACKAGE_NAME $PACKAGE_VER
}

function build () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2
    local LOCAL_PACKAGE_PATH=$3

    # compile cfltk
    cd cfltk
    
    cmake -B bin -S . \
     -DCMAKE_BUILD_TYPE=Release \
     -DOPTION_USE_SYSTEM_LIBPNG=OFF \
     -DOPTION_USE_SYSTEM_LIBJPEG=OFF \
     -DOPTION_USE_SYSTEM_ZLIB=OFF \
     -DOPTION_USE_GL=OFF \
     -DFLTK_BUILD_EXAMPLES=OFF \
     -DFLTK_BUILD_TEST=OFF \
     -DOPTION_USE_THREADS=ON \
     -DOPTION_LARGE_FILE=ON \
     -DOPTION_BUILD_HTML_DOCUMENTATION=OFF \
     -DOPTION_BUILD_PDF_DOCUMENTATION=OFF \
     -DCMAKE_CXX_FLAGS="-fPIC" \
     -DCMAKE_C_FLAGS="-fPIC" \
     -DCMAKE_SHARED_LINKER_FLAGS="-fPIC" \
     -DCFLTK_BUILD_SHARED=ON
    
    cmake --build bin --parallel

    # generate cffi bindings
    cd $ENV_PATH

    ./qjs-cffi \
        -sizeof-cflags="-I$CACHE_PACKAGE_PATH/cfltk/include" \
        -sizeof-include="cfl_box.h,cfl_browser.h,cfl_button.h,cfl_dialog.h,cfl_draw.h,cfl_enums.h,cfl_group.h,cfl.h,cfl_image.h,cfl_input.h,cfl_macros.h,cfl_menu.h,cfl_misc.h,cfl_printer.h,cfl_surface.h,cfl_table.h,cfl_text.h,cfl_tree.h,cfl_utils.h,cfl_valuator.h,cfl_widget.h,cfl_window.h" \
        -i $CACHE_PACKAGE_PATH/cfltk/include \
        -o $CACHE_PACKAGE_PATH/quickjs-fltk-cffi \
        -l $LOCAL_PACKAGE_PATH/quickjs-fltk-cffi/libcfltk.so

    ./qjs-cffi \
        -sizeof-cflags="-I$CACHE_PACKAGE_PATH/cfltk/include" \
        -sizeof-include="cfl_box.h,cfl_browser.h,cfl_button.h,cfl_dialog.h,cfl_draw.h,cfl_enums.h,cfl_group.h,cfl.h,cfl_image.h,cfl_input.h,cfl_macros.h,cfl_menu.h,cfl_misc.h,cfl_printer.h,cfl_surface.h,cfl_table.h,cfl_text.h,cfl_tree.h,cfl_utils.h,cfl_valuator.h,cfl_widget.h,cfl_window.h" \
        -i $CACHE_PACKAGE_PATH/cfltk/include \
        -o $CACHE_PACKAGE_PATH/quickjs-fltk-cffi/fltk.js \
        -l $LOCAL_PACKAGE_PATH/quickjs-fltk-cffi/libcfltk.so

    echo build $PACKAGE_NAME $PACKAGE_VER
}

function install () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2
    local LOCAL_PACKAGE_PATH=$3

    cp $ENV_PATH/$CACHE_PACKAGE_PATH/cfltk/bin/libcfltk.so $ENV_PATH/$LOCAL_PACKAGE_PATH/libcfltk.so
    cp $ENV_PATH/$CACHE_PACKAGE_PATH/quickjs-fltk-cffi/* $ENV_PATH/$LOCAL_PACKAGE_PATH

    echo install $PACKAGE_NAME $PACKAGE_VER
}

function uninstall () {
    # args
    local ENV_PATH=$1
    local CACHE_PACKAGE_PATH=$2
    local LOCAL_PACKAGE_PATH=$3

    echo uninstall $PACKAGE_NAME $PACKAGE_VER
}

# dispatch function with args without $0 and $1
echo $($1 ${@:2})
